export { default as MenuSVG } from "./menu.svg"
export { default as CloseSVG } from "./close.svg"
export { default as SpinnerSVG } from "./spinner.svg"
export { default as DownSVG } from "./down.svg"
export { default as LinkSVG } from "./link.svg"
export { default as SendSVG } from "./send.svg"
export { default as MapSVG } from "./map.svg"
export { default as MailSVG } from "./mail.svg"
export { default as PersonSVG } from "./person.svg"

export { default as GitHubSVG } from "./socials/github.svg"
export { default as LinkedInSVG } from "./socials/linkedin.svg"
