export { default as StarFilledSVG } from "./starFilled.svg"
export { default as EditSVG } from "./edit.svg"
export { default as DeleteSVG } from "./delete.svg"
export { default as GallerySVG } from "./gallery.svg"
export { default as ReviewsSVG } from "./reviews.svg"
export { default as OptionsSVG } from "./options.svg"
export { default as HomeSVG } from "./home.svg"
export { default as PeopleSVG } from "./people.svg"
export { default as ClockSVG } from "./clock.svg"
export { default as MenuSVG } from "./menu.svg"
export { default as HomeWorkSVG } from "./homeWork.svg"
export { default as CloseSVG } from "./close.svg"
export { default as PlusSVG } from "./plus.svg"
export { default as SpinnerSVG } from "./spinner.svg"
export { default as DownSVG } from "./down.svg"

export { default as GitHubSVG } from "./socials/github.svg"
export { default as LinkedInSVG } from "./socials/linkedin.svg"

export { default as LogoSVG } from "./logo.svg"
export { default as AttachMediaSVG } from "./attachMedia.svg"
