export { default as StarFilledSVG } from "./starFilled.svg"
export { default as EditSVG } from "./edit.svg"
export { default as DeleteSVG } from "./delete.svg"
export { default as GallerySVG } from "./gallery.svg"
export { default as ReviewsSVG } from "./reviews.svg"
export { default as OptionsSVG } from "./options.svg"
export { default as HomeSVG } from "./home.svg"
export { default as PeopleSVG } from "./people.svg"
export { default as ClockSVG } from "./clock.svg"
export { default as MenuSVG } from "./menu.svg"
export { default as HomeWorkSVG } from "./homeWork.svg"
export { default as CloseSVG } from "./close.svg"
export { default as PlusSVG } from "./plus.svg"
export { default as SpinnerSVG } from "./spinner.svg"

export { default as FacebookSVG } from "./socials/facebook.svg"
export { default as InstagramSVG } from "./socials/instagram.svg"
export { default as TwitterSVG } from "./socials/twitter.svg"
export { default as YoutubeSVG } from "./socials/youtube.svg"

export { default as LogoSVG } from "./logo.svg"
export { default as AttachMediaSVG } from "./attachMedia.svg"
